name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pull_request_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install PNPM
      run: npm i -g pnpm
    
    - name: Install dependencies
      run: pnpm install
      
    - name: Lint Check
      id: run-lint-check
      run: pnpm run lint
    
    - name: Check for Lint check failure
      if: step.run-lint-check.output.status == 'failure'
      run: exit 1
    
    - name: Run Unit Tests
      id: run-unit-tests
      run: pnpm run test
    
    - name: Check for unit test failure
      if: step.run-unit-tests.output.status == 'failure'
      run: exit 1