name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pull_request_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    
    - name: Install PNPM
      run: npm i -g pnpm
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Run Unit Tests
      id: run-unit-tests
      run: pnpm run test
    
    - name: Check for unit test failure
      if: ${{ steps.run-unit-tests.output.status }} == 'failure'
      run: exit 1
